/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package guru.ioio.aop_plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class AopPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        println("*** AopPlugin ***")
        // Register a task
//        project.tasks.register("greeting") { task ->
//            task.doLast {
//                println("Hello from plugin 'guru.ioio.aop_plugin'")
//            }
//        }
    }
}
